# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9525d8a1168c9378f2843a291f97009f6dfea758602352f250a2e0acce6f440afba16e03ab8f1d226e5dd07db7fef4159601d097e320943d585a407a9791f634

test:
  secret_key_base: 8bf9bfe4b9790085d782e9f1f3086b2479448986a7d4647e5e817500098ac682220d5007a91c15c6d724b139d977d1847b74c399115aed6d6be2e695f9efced9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
